[package]
name = "google-genai"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
hyper-util = "0.1.10"
serde = { version = "1.0.216", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.133"
serde_with = "3.11.0"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1.42.0", features = ["full"] }
